### ISSUE TITLE
Object indentation broken

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/picky.json#50]
![image](https://cloud.githubusercontent.com/assets/224636/24259547/92e45460-0fc7-11e7-9b97-036bd6cfbf03.png)

**Comment by danjford** [comment]
@corysimmons is this the spacing between the properties and the brackets? I think it just needs some padding adding. This is an example with 20px rather than the 10px, I've noticed that there is some whitespace in the HTML which needs to be removed as well to improve the alignment:

![image](https://cloud.githubusercontent.com/assets/7963046/24291713/01bb3380-1082-11e7-9291-0159542f048b.png)

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/24298242/c5e3834a-107b-11e7-96d1-3f93cd5adfe1.png)

I'll take a look at it.

**Comment by corysimmons** [comment]
20px indent on `.parent` is better, but then it doesn't line up with `.picky-wrap`.

![image](https://cloud.githubusercontent.com/assets/224636/24299531/e88d5ade-107f-11e7-89c9-f1518f252818.png)

This isn't terribly flexible (will break with various font sizes/zooms), but should work for the default view right now:

```styl
.parent
  padding-left: 15px

.picky-wrap:first-child
  margin-left: -8px
```

Would you mind updating this on `gh-pages` and in the Chrome extension? I'd do it but I can't get `npm install` to work (looks like it's hanging on a BrowserSync dependency or something).

**Comment by danjford** [comment]
I think it not lining up with `.picky-wrap` is the issue where there is some whitespace within the HTML, if this gets removed then it lines up well.

Will create a pull request in a sec!

**Comment by danjford** [comment]
Ah actually, the `margin-left: -8px` works out better as the whitespace end works well in other areas.
